{
 "title": "광훈's 대시보드",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "dimension_values($default_region,AWS/ECS,CPUUtilization,ClusterName)"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "service",
    "label": "Service",
    "query": "dimension_values($region,AWS/ECS,CPUUtilization,ServiceName)"
   },
   {
    "name": "dbinstanceidentifier",
    "label": "Dbinstanceidentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   },
   {
    "name": "distributionid",
    "label": "Distributionid",
    "query": "dimension_values(us-east-1, AWS/CloudFront, Requests, DistributionId)"
   },
   { "name": "query0" },
   { "name": "query1" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/ApplicationELB,ActiveConnectionCount,LoadBalancer)"
   },
   { "name": "query2" },
   {
    "name": "targetgroupName",
    "label": "TargetgroupName",
    "query": "dimension_values($region,AWS/ApplicationELB, HealthyHostCount, TargetGroup)"
   },
   {
    "name": "taskdefinition",
    "label": "Taskdefinition",
    "query": "dimension_values($region, ECS/ContainerInsights, , TaskDefinitionFamily)"
   },
   {
    "name": "dbclusterIDntifier",
    "label": "Dbclusterentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBClusterIdentifier)"
   },
   { "name": "readdb" },
   {
    "name": "readdbinstanceidentifier",
    "label": "Readdbinstanceidentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   },
   {
    "name": "writedbinstanceidentifier",
    "label": "Writedbinstanceidentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine Up Time",
   "type": "stat",
   "description": "인스턴스 실행 시간입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "EngineUpT",
     "dimensions": { "DbClusterIdentifier": "$dbclusterIDntifier" },
     "metricName": "EngineUptime",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "EngineUptime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MAX(EngineUptime) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Queries (Count/Second)",
   "type": "stat",
   "description": "초당 실행 쿼리의 평균 수입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Queri",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "Queries", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(Queries) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 16, "x": 8, "y": 1 },
   "targets": [
    { "namespace": "AWS/RDS", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "description": "Aurora DB 인스턴스의 CPU 사용률입니다.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "/$dbinstanceidentifier/",
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query throughput",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 6 },
   "targets": [
    { "namespace": "AWS/RDS", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "SelectThroughput (Count/Second)",
   "type": "stat",
   "description": "초당 평균 SELECT 쿼리 수입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "SELECTThroughp",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "SelectThroughput", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(SelectThroughput) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DMLThroughput (Count/Second)",
   "type": "stat",
   "description": "초당 평균 INSERT, UPDATE 및 DELETE 수입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "DMLThroughpu",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "DMLThroughput", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(DMLThroughput) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory (Bytes)",
   "type": "timeseries",
   "description": "사용 가능한 RAM 크기입니다.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ReadIOPS", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ReadIOPS) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query perofromance",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 12 },
   "targets": [
    { "namespace": "AWS/RDS", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Swap Usage (Bytes)",
   "type": "timeseries",
   "description": "사용되는 스왑 공간 크기입니다. 이 지표는 Aurora PostgreSQL DB 인스턴스 클래스 db.t3.medium, db.t3.large, db.r4.large, db.r4.xlarge, db.r5.large, db.r5.xlarge, db.r6g.large, db.r6g.xlarge, db.t4g.medium 및 db.t4g.large에 사용할 수 있습니다. Aurora MySQL의 경우, 이 지표는 db.t* DB 인스턴스 클래스에만 적용됩니다.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ReadIOPS", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ReadIOPS) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Select Latency (ms)",
   "type": "stat",
   "description": "SELECT 작업의 평균 소요 시간입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "selectLaten",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "SelectLatency", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(SelectLatency) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DML Latency (ms)",
   "type": "stat",
   "description": "INSERT, UPDATE 및 DELETE의 평균 소요 시간입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Latency",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "DMLLatency", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(DMLLatency) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Read/Write Latency (ms)",
   "type": "timeseries",
   "description": "디스크 I/O 연산당 평균 처리 시간입니다.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$readdbinstanceidentifier" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ReadIOPS", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ReadIOPS) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$writedbinstanceidentifier" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "namespace": "AWS/RDS", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Database Connections (Count)",
   "type": "stat",
   "description": "데이터베이스 인스턴스에 대한 클라이언트 네트워크 연결 수입니다.\n\n지표 값에 다음이 포함되지 않기 때문에 데이터베이스 세션 수가 지표 값보다 클 수 있습니다.\n\n더 이상 네트워크에 연결되어 있지 않지만 데이터베이스에 의해 정리되지 않은 세션\n\n데이터베이스 엔진에 의해 자체 용도로 생성된 세션\n\n데이터베이스 엔진의 병렬 실행 기능에 의해 생성된 세션\n\n데이터베이스 엔진 작업 스케줄러에 의해 생성된 세션\n\nAmazon Aurora 연결",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Connections",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DatabaseConnections", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DatabaseConnections) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Login Failures (Count)",
   "type": "stat",
   "description": "초당 평균 로그인 실패 수입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "LoginFailur",
     "metricName": "Queries",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "MAX",
       "parameters": [
        { "name": "LoginFailures", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "$dbinstanceidentifier" }, "property": { "name": "DBInstanceIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT MAX(LoginFailures) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier' AND DBInstanceIdentifier = '$dbinstanceidentifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space (Bytes)",
   "type": "timeseries",
   "description": "사용 가능한 로컬 스토리지 양입니다.\n\n다른 DB 엔진과 달리 Aurora DB 인스턴스의 경우, 이 지표는 각 DB 인스턴스에 사용 가능한 스토리지 크기를 보고합니다. 이 값은 DB 인스턴스 클래스에 좌우됩니다(요금에 대한 자세한 내용은 Amazon RDS 제품 페이지 참조). DB 인스턴스 클래스를 큰 것으로 선택하면 인스턴스의 여유 스토리지 공간을 늘릴 수 있습니다.\n\n(Aurora Serverless v2에는 적용되지 않습니다.)",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "FreeLocalStorage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ReadIOPS", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ReadIOPS) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Replica",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "namespace": "AWS/RDS", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Aurora Replica Lag (ms)",
   "type": "timeseries",
   "description": "이진수 로그 복제 소스를 기준으로 Aurora MySQL 호환 버전에서 실행 중인 이진수 로그 복제본 DB 클러스터의 지연 시간입니다. 지연이란 소스에서 복제본이 적용할 수 있는 레코드보다 빠르게 레코드를 생성하고 있음을 의미합니다.\n\n이 지표는 엔진 버전에 따라 다른 값을 보고합니다.\n\nAurora MySQL 버전 1 및 2\nMySQL SHOW SLAVE STATUS의 Seconds_Behind_Master 필드\n\nAurora MySQL 버전 3\nSHOW REPLICA STATUS\n\n이 지표를 사용하여 이진 로그 복제본 역할을 하는 클러스터의 오류 및 복제본 지연을 모니터링할 수 있습니다. 지표 값은 다음을 나타냅니다.\n\n높은 값\n복제본이 복제 소스를 지연시키고 있습니다.\n\n0 또는 0에 가까운 값\n복제본 프로세스가 활성 상태입니다.\n\n-1\nAurora가 지연 시간을 확인할 수 없는 경우는 복제본 설정 중 또는 복제본이 오류 상태에 있을 때 발생할 수 있습니다.\n\n이진 로그 복제는 클러스터의 라이터 인스턴스에서만 발생하므로 WRITER 역할과 연결된 이 지표 버전을 사용하는 것이 좋습니다.\n\n복제 관리에 대한 자세한 정보는 여러 AWS 리전에 걸쳐 Amazon Aurora MySQL DB 클러스터 복제 섹션을 참조하세요. 문제 해결에 대한 자세한 내용은 Amazon Aurora MySQL 복제 문제 단원을 참조하세요.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "ReplicaLag",
     "metricName": "AuroraReplicaLag",
     "metricQueryType": 1,
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "AuroraReplicaLag", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(AuroraReplicaLag) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Receive/Transmit Throughput (Bytes/Second)",
   "type": "timeseries",
   "description": "Aurora MySQL DB 클러스터의 각 인스턴스가 클라이언트에서 수신하는 네트워크 처리량입니다. 이 처리량에서 Aurora DB 클러스터의 인스턴스와 클러스터 볼륨 간 네트워크 트래픽은 제외됩니다.\n\nAurora DB 클러스터의 각 인스턴스가 클라이언트로 전송하는 네트워크 처리량입니다. 이 처리량에서 DB 클러스터의 인스턴스와 클러스터 볼륨 간 네트워크 트래픽은 제외됩니다.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ReadIOPS", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$dbclusterIDntifier" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ReadIOPS) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = '$dbclusterIDntifier'",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusterIDntifier" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ELB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Errors",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Errors From the Load Balancer (Count)",
   "type": "timeseries",
   "description": "로드 밸런서에서 생성된 HTTP 4XX 클라이언트 오류 코드 수. 단, 대상에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.\n\n클라이언트 오류는 요청 형식이 잘못되었거나 불완전할 때 생성됩니다. 로드 밸런서가 HTTP 460 오류 코드를 반환하는 경우를 제외하고 대상에서는 이러한 요청이 수신되지 않습니다. 단, 대상에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.\n\n로드 밸런서에서 생성된 HTTP 5XX 서버 오류 코드 수. 단, 대상에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "alias": "4XX",
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "5XX",
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors From the Target Groups (Count)",
   "type": "timeseries",
   "description": "대상에서 생성된 HTTP 응답 코드 수. 단, 로드 밸런서에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "alias": "4XX",
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "5XX",
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Top 5 Response Time Target Groups (ms)",
   "type": "bargauge",
   "description": "로드 밸런서에서 요청 신호를 전송한 후 대상에서 응답 신호가 수신될 때까지 결과된 시간(초). 이 지표는 액세스 로그에서 target_processing_time 필드와 동일합니다.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroupName" },
     "metricName": "TargetResponseTime",
     "metricQueryType": 1,
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/ApplicationELB", "type": "functionParameter" },
        { "name": "LoadBalancer", "type": "functionParameter" },
        { "name": "TargetGroup", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "TargetGroup", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 5,
      "orderBy": { "name": "AVG", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "TargetResponseTime", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "$targetgroupName" }, "property": { "name": "TargetGroup", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(TargetResponseTime) FROM SCHEMA(\"AWS/ApplicationELB\", LoadBalancer, TargetGroup) WHERE LoadBalancer = '$loadbalancername' AND TargetGroup = '$targetgroupName' GROUP BY TargetGroup ORDER BY AVG() DESC LIMIT 5",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts (Count)",
   "type": "timeseries",
   "description": "비정상 상태로 간주되는 대상 수.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroupName" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "TLS Negotiation Errors (Count)",
   "type": "timeseries",
   "description": "TLS 오류로 인해 로드 밸런서와 세션을 구성하지 않은 클라이언트에서 시작된 TLS 연결 수. 가능한 원인으로는 암호 또는 프로토콜 불일치나 클라이언트의 서버 인증서 확인 실패 및 연결 종료가 있습니다.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Rejected Requests (Count)",
   "type": "timeseries",
   "description": "로드 밸런서가 최대 연결 수에 도달하여 거부된 연결 수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "RejectedConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Request (Count)",
   "type": "timeseries",
   "description": "IPv4 및 IPv6를 통해 처리된 요청 수입니다. 이 지표는 로드 밸런서 노드가 대상을 선택할 수 있었던 요청에 대해서만 증가합니다. 대상이 선택되기 전에 거부된 요청은 이 지표에 반영되지 않습니다.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroupName" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Consumed LCU  (LCUs)",
   "type": "stat",
   "description": "로드 밸런서에서 IPv4 및 IPv6를 통해 처리된 총 바이트 수(HTTP 헤더 및 HTTP 페이로드)입니다. 이 수에는 클라이언트와 Lambda 함수로 송수신하는 트래픽과 IdP(ID 공급자)가 보내는 트래픽(사용자 인증이 활성화된 경우)이 포함됩니다.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "LCUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ProcessedBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ProcessedBytes) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "New Connections (Count)",
   "type": "timeseries",
   "description": "클라이언트에서 로드 밸런서로, 그리고 로드 밸런서에서 대상으로 새롭게 구성된 TCP 연결 총 수",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "LoadBalancer": "$loadbalancername" },
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NewConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NewConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Rule Evaluations (Count)",
   "type": "timeseries",
   "description": "\t\n1시간 평균 요청 빈도를 기준으로 로드 밸런서에서 처리된 규칙 수",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "RuleEvaluations",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ProcessedBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ProcessedBytes) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "2XX Responses by Target Groups (Count)",
   "type": "timeseries",
   "description": "대상에서 생성된 HTTP 응답 코드 수. 단, 로드 밸런서에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroupName" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ProcessedBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ProcessedBytes) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Connections (Count)",
   "type": "timeseries",
   "description": "클라이언트에서 로드 밸런서로, 그리고 로드 밸런서에서 대상으로 동시에 연결되는 활성 TCP 연결 총 수.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "LoadBalancer": "$loadbalancername" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ActiveConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ActiveConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Processed Bytes (Bytes)",
   "type": "timeseries",
   "description": "로드 밸런서에서 IPv4 및 IPv6를 통해 처리된 총 바이트 수(HTTP 헤더 및 HTTP 페이로드)입니다. 이 수에는 클라이언트와 Lambda 함수로 송수신하는 트래픽과 IdP(ID 공급자)가 보내는 트래픽(사용자 인증이 활성화된 경우)이 포함됩니다.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "AvailabilityZone": "*", "LoadBalancer": "$loadbalancername" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ProcessedBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ProcessedBytes) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "3XX Responses by Target Groups (Count)",
   "type": "timeseries",
   "description": "대상에서 생성된 HTTP 응답 코드 수. 단, 로드 밸런서에서 생성된 응답 코드 수는 여기에 포함되지 않습니다.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroupName" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "LoadBalancer", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ProcessedBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancername" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ProcessedBytes) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancername' GROUP BY LoadBalancer",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "ECS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Service",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 67 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 4, "y": 67 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "ServiceTaskCount (Count)",
   "type": "bargauge",
   "description": "# 현재 RUNNING 상태인 작업의 숫자입니다.\n\n# pending\n현재 PENDING 상태인 작업의 숫자입니다.\n\n# desired\nAmazon ECS 서비스에 대해 원하는 태스크 수입니다.",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "개" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Running",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "alias": "Pending",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "PendingTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "alias": "Desired",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "CPU/Memory Usage (%)",
   "type": "timeseries",
   "description": "# CPU\n클러스터 또는 서비스에서 사용하는 CPU 단위의 비율(%)입니다.\n\n서비스 CPU 사용률(ClusterName 및 ServiceName으로 필터링되는 지표)은 서비스에 속하는 작업이 사용하는 총 CPU 단위를 서비스에 속하는 작업에 대해 예약된 총 CPU 단위 수로 나눈 값으로 측정됩니다. 서비스 CPU 사용률 지표는 Fargate 및 EC2 시작 유형을 모두 사용하는 작업에 사용됩니다.\n\n# Memory\n클러스터 또는 서비스에서 사용하는 메모리의 비율(%)입니다.\n\n서비스 메모리 사용률(ClusterName 및 ServiceName으로 필터링되는 지표)은 서비스에 속하는 작업이 사용하는 총 메모리를 서비스에 속하는 작업에 대해 예약된 총 메모리로 나눈 값으로 측정됩니다. 서비스 메모리 사용률 지표는 Fargate 및 EC2 시작 유형을 모두 사용하는 작업에 사용됩니다.\n",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "Memory",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network RX/TX (Bytes)",
   "type": "timeseries",
   "description": "사용중인 측정기준에서 지정한 리소스에서 수신된 바이트의 숫자입니다.\n\n사용중인 측정기준에서 지정한 리소스에서 전송된 바이트의 숫자입니다.\n\n이 지표는 awsvpc 또는 bridge 네트워크 모드를 사용하는 태스크의 컨테이너에 대해서만 제공됩니다.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "RX",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "TX",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Read/Write (Bytes)",
   "type": "timeseries",
   "description": "사용 중인 측정기준에서 지정한 리소스의 스토리지에서 읽혀진 바이트의 숫자입니다.\n\n사용 중인 측정기준에서 지정한 리소스의 스토리지에서 쓰여진 바이트의 숫자입니다.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "StorageReadBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "alias": "Write",
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "StorageWriteBytes",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "CloudFront", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Errors",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 84 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 16, "x": 8, "y": 84 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "TotalErrorRate (%)",
   "type": "gauge",
   "description": "해당 기간 동안 지정한 배포에 대해 HTTP 상태 코드가 4xx 또는 5xx 오류였던 요청의 백분율입니다.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "4xxErrorRate (%)",
   "type": "gauge",
   "description": "해당 기간 동안 지정한 배포에 대해 HTTP 상태 코드가 4xx 오류였던 요청의 백분율입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesDownloaded (Bytes)",
   "type": "timeseries",
   "description": "해당 기간 동안 지정한 배포에 대해 최종 사용자가 다운로드한 바이트 수입니다.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Requests (Count)",
   "type": "timeseries",
   "description": "해당 기간 동안의 전체 HTTP 상태 코드(예: 200, 404 등)와 전체 메소드(예: GET, HEAD, POST 등)의 총 요청 수입니다.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "dimensions": { "DistributionId": "E2K4OIXYOWGU6T", "Region": "Global" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "5xxErrorRate (%)",
   "type": "gauge",
   "description": "해당 기간 동안 지정한 배포에 대해 HTTP 상태 코드가 5xx 오류였던 요청의 백분율입니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesUploaded (Bytes)",
   "type": "timeseries",
   "description": "해당 기간 동안 지정한 배포에 대해 최종 사용자가 업로드한 바이트 수입니다.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Caching",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 95 },
   "targets": [
    { "queryMode": "Metrics", "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "CacheHitRate (%)",
   "type": "gauge",
   "description": "CloudFront가 캐시에서 콘텐츠를 제공하는 캐시 가능한 모든 요청의 비율입니다. HTTP POST 및 PUT 요청, 오류는 캐시 가능한 요청으로 간주되지 않습니다.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "OriginLatency (ms)",
   "type": "stat",
   "description": "CloudFront에서 요청을 수신한 시점부터 CloudFront 캐시가 아닌 오리진에서 제공되는 요청에 대해 네트워크(최종 사용자 아님)에 대한 응답을 제공하기 시작한 시점까지 소요되는 총 시간(밀리초)입니다. 이것을 첫 번째 바이트 대기 시간 또는 time-to-first-byte라고도 합니다.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "metricName": "OriginLatency",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}