{
 "title": "ECS task-definition Log",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status Code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter res.statusCode like /(2[0-9]{2})/\n| stats count(*) as count by bin(1m)",
     "logGroupNames": [ "/ecs/demo-td" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter res.statusCode like /(3[0-9]{2})/\n| stats count(*) as count by bin(1m)",
     "logGroupNames": [ "/ecs/demo-td" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter res.statusCode like /(4[0-9]{2})/\n| stats count(*) as count by bin(1m)",
     "logGroupNames": [ "/ecs/demo-td" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter res.statusCode like /(5[0-9]{2})/\n| stats count(*) as count by bin(1m)",
     "logGroupNames": [ "/ecs/demo-td" ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  { "title": "Log Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "req & res Log",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| limit 500\n| display @timestamp, reqId, req.method, req.hostname, req.url, req.remoteAddress, res.statusCode, msg",
     "logGroupNames": [ "/ecs/demo-td" ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}