{
 "title": "CloudFront WAF Log",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource_region", "label": "Region", "query": "us-east-1" }
  ]
 },
 "panels": [
  { "title": "국가별 트래픽", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country like /(^KR$)/\n| stats count(*) as KR by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "US",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country like /(^US$)/\n| stats count(*) as US by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "CN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country like /(^CN$)/\n| stats count(*) as CN by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "JP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country like /(^JP$)/\n| stats count(*) as JP by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "EU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country like /(^AT$)|(^BE$)|(^BG$)|(^CY$)|(^CZ$)|(^DE$)|(^DK$)|(^EE$)|(^ES$)|(^FI$)|(^FR$)|(^GB$)|(^GR$)|(^HR$)|(^HU$)|(^IE$)|(^IT$)|(^LT$)|(^LU$)|(^LV$)|(^MT$)|(^NL$)|(^SE$)|(^SI$)|(^SK$)|(^PL$)|(^PT$)/\n| stats count(*) as EU by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expression": "filter httpRequest.country not like /(^KR$)|(^US$)|(^CN$)|(^JP$)|(^AT$)|(^BE$)|(^BG$)|(^CY$)|(^CZ$)|(^DE$)|(^DK$)|(^EE$)|(^ES$)|(^FI$)|(^FR$)|(^GB$)|(^GR$)|(^HR$)|(^HU$)|(^IE$)|(^IT$)|(^LT$)|(^LU$)|(^LV$)|(^MT$)|(^NL$)|(^SE$)|(^SI$)|(^SK$)|(^PL$)|(^PT$)/\n| stats count(*) as Others by bin(1h)\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "bin(1h)" ]
    }
   ]
  },
  { "title": "차단/허용 메시지", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BLOCK",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter action like /BLOCK/\n| stats count(*) as block_count by action\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "action" ]
    }
   ]
  },
  {
   "title": "BLOCK",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, terminatingRuleId as @Block_Reason\n| filter action like /BLOCK/\n| sort @timestamp desc\n| limit 50",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  },
  {
   "title": "ALLOW",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter action like /ALLOW/\n| stats count(*) as allow_count by action\n| limit 24",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [ "action" ]
    }
   ]
  },
  {
   "title": "ALLOW",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 14 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter action like /ALLOW/\n| sort @timestamp desc\n| limit 50",
     "logGroupNames": [ "aws-waf-logs-cloudfront" ],
     "queryMode": "Logs",
     "region": "us-east-1"
    }
   ]
  }
 ]
}